line_length: 136

disabled_rules:
  - todo
  - force_try
  - force_cast
  - trailing_comma
  - large_tuple
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - function_body_length
  - block_based_kvo
  - shorthand_operator
  - function_parameter_count
  - nesting

excluded:
  - Pods

identifier_name:
  excluded:
    - id
    - to
    - ui
    - on
    - us
    - no
    - v1
    - v2
    - v3
    - v4
    - v5

type_name:
  excluded:
    - UI
